# Generated by Django 5.2 on 2026-02-16 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_projects_alter_bannerimages_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gallery',
        ),
        migrations.DeleteModel(
            name='Students',
        ),
    ]
