# Generated by Django 5.2 on 2026-02-16 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_delete_gallery_delete_students'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Courses',
        ),
    ]
